language: cpp
git:
  depth: 1
os: linux
dist:
- xenial
- bionic
compiler: gcc
addons:
  apt:
    packages:
      - mesa-common-dev
      - libglu1-mesa-dev
script:
- bash travis/$TRAVIS_OS_NAME/build.sh
notifications:
  email: false